### ISSUE TITLE
Very different in Node 22 - forEach now faster than for..of

### ISSUE THREAD

**Issue by nathdolan** [LeanyLabs/js-array-performance#3]
Ideally could the home page be updated?

Current results on Node 22.3.0 / Ubuntu 22.04 / i7-13700H:

Benchmarking forEach:
Array.forEach x 221 ops/sec ±5.37% (85 runs sampled)
for of x 205 ops/sec ±6.49% (84 runs sampled)
for <array.length, indexing x 278 ops/sec ±1.76% (80 runs sampled)
for <len, indexing x 266 ops/sec ±1.22% (78 runs sampled)
for <array.length, tmp element x 268 ops/sec ±1.23% (82 runs sampled)
for <len, tmp element x 253 ops/sec ±1.90% (78 runs sampled)
for <array.length, indexing is faster

Benchmarking map:
Array.map x 44.74 ops/sec ±8.81% (61 runs sampled)
Array.map, destructuring x 46.95 ops/sec ±7.73% (63 runs sampled)
for of x 63.31 ops/sec ±7.96% (58 runs sampled)
for of, destructuring x 64.06 ops/sec ±6.16% (57 runs sampled)
for, init array x 150 ops/sec ±1.78% (79 runs sampled)
for, init array is faster

Benchmarking reduce:
Array.reduce x 151 ops/sec ±2.16% (72 runs sampled)
Array.reduce, destructuring x 149 ops/sec ±2.45% (77 runs sampled)
for of x 184 ops/sec ±7.82% (71 runs sampled)
for x 305 ops/sec ±2.28% (75 runs sampled)
for is faster

**Comment by Andriy-LL** [comment]
Sure, thanks for providing the results on modern Node and hardware. The homepage has been updated.
